version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_django
      - POSTGRES_PASSWORD=dev_django
      - POSTGRES_DB=django_dev
    ports:
      - 5432:5432
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  celery:
    build: ./rest_scraper
    command: celery -A rest_scraper worker
    volumes:
      - .:/code
    links:
      - db
      - redis


volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis:
