version: '3.7'

services:
  web:
    build: ./rest_scraper
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./rest_scraper/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_django
      - POSTGRES_PASSWORD=dev_django
      - POSTGRES_DB=django_dev
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: