version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_django
      - POSTGRES_PASSWORD=dev_django
      - POSTGRES_DB=django_dev
    ports:
      - 5432:5432
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  web:
    build: ./rest_scraper
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./rest_scraper/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  test:
    build: ./rest_scraper
    command: python manage.py test api.tests
    volumes:
      - ./rest_scraper/:/usr/src/app/
    depends_on:
      - web

  celery:
    build: ./rest_scraper
    command: celery -A rest_scraper worker
    volumes:
      - ./rest_scraper/:/usr/src/app/
      - media_volume:/home/app/web/media
    links:
      - db
      - redis

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web



volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis:
