# Generated by Django 3.0.3 on 2020-02-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048, verbose_name='Url strony')),
                ('text', models.TextField(verbose_name='Tekst ze strony')),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Strona',
                'verbose_name_plural': 'Strony',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media', verbose_name='Obraz')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Page', verbose_name='Strona')),
            ],
            options={
                'verbose_name': 'Obraz',
                'verbose_name_plural': 'Obrazy',
                'ordering': ['id'],
            },
        ),
    ]
