# Generated by Django 3.0.3 on 2020-03-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200227_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='scraped',
            field=models.BooleanField(default=False, verbose_name='Gotowy-scrawlowany'),
        ),
        migrations.AlterField(
            model_name='page',
            name='scraped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scrawlowany o'),
        ),
    ]
